// Generated by https://quicktype.io

export interface SmallCountry {
  name: string;
  cca3: string;
  borders?: string[];
}

export interface Country {
  name: Name;
  tld?: string[];
  cca2: string;
  ccn3?: string;
  cca3: string;
  cioc?: string;
  independent?: boolean;
  status: Status;
  unMember: boolean;
  currencies?: Currencies;
  idd: Idd;
  capital?: string[];
  altSpellings: string[];
  region: Region;
  subregion?: string;
  languages?: { [key: string]: string };
  translations: { [key: string]: Translation };
  latlng: number[];
  landlocked: boolean;
  area: number;
  demonyms?: Demonyms;
  flag: string;
  maps: Maps;
  population: number;
  fifa?: string;
  car: Car;
  timezones: string[];
  continents: Continent[];
  flags: Flags;
  coatOfArms: CoatOfArms;
  startOfWeek: StartOfWeek;
  capitalInfo: CapitalInfo;
  gini?: { [key: string]: number };
  postalCode?: PostalCode;
  borders?: string[];
}

export interface CapitalInfo {
  latlng?: number[];
}

export interface Car {
  signs?: string[];
  side: Side;
}

export enum Side {
  Left = 'left',
  Right = 'right',
}

export interface CoatOfArms {
  png?: string;
  svg?: string;
}

export enum Continent {
  Africa = 'Africa',
  Antarctica = 'Antarctica',
  Asia = 'Asia',
  Europe = 'Europe',
  NorthAmerica = 'North America',
  Oceania = 'Oceania',
  SouthAmerica = 'South America',
}

export interface Currencies {
  XCD?: TartuGecko;
  TOP?: TartuGecko;
  AUD?: TartuGecko;
  XAF?: TartuGecko;
  MGA?: TartuGecko;
  KWD?: TartuGecko;
  IQD?: TartuGecko;
  EUR?: TartuGecko;
  NPR?: TartuGecko;
  XOF?: TartuGecko;
  NGN?: TartuGecko;
  WST?: TartuGecko;
  USD?: TartuGecko;
  JMD?: TartuGecko;
  MNT?: TartuGecko;
  AZN?: TartuGecko;
  BGN?: TartuGecko;
  LYD?: TartuGecko;
  MAD?: TartuGecko;
  BYN?: TartuGecko;
  THB?: TartuGecko;
  LBP?: TartuGecko;
  BRL?: TartuGecko;
  PGK?: TartuGecko;
  ZWL?: TartuGecko;
  AOA?: TartuGecko;
  RWF?: TartuGecko;
  LAK?: TartuGecko;
  NIO?: TartuGecko;
  CRC?: TartuGecko;
  TMT?: TartuGecko;
  INR?: TartuGecko;
  DZD?: TartuGecko;
  MRU?: TartuGecko;
  SRD?: TartuGecko;
  AWG?: TartuGecko;
  KGS?: TartuGecko;
  NOK?: TartuGecko;
  UYU?: TartuGecko;
  KZT?: TartuGecko;
  BAM?: BAM;
  BOB?: TartuGecko;
  XPF?: TartuGecko;
  TJS?: TartuGecko;
  HNL?: TartuGecko;
  MVR?: TartuGecko;
  RSD?: TartuGecko;
  ANG?: TartuGecko;
  KYD?: TartuGecko;
  TZS?: TartuGecko;
  GHS?: TartuGecko;
  GBP?: TartuGecko;
  IMP?: TartuGecko;
  IRR?: TartuGecko;
  NAD?: TartuGecko;
  ZAR?: TartuGecko;
  BSD?: TartuGecko;
  HUF?: TartuGecko;
  MDL?: TartuGecko;
  CZK?: TartuGecko;
  EGP?: TartuGecko;
  ILS?: TartuGecko;
  JOD?: TartuGecko;
  GNF?: TartuGecko;
  TTD?: TartuGecko;
  TWD?: TartuGecko;
  KES?: TartuGecko;
  NZD?: TartuGecko;
  SSP?: TartuGecko;
  JEP?: TartuGecko;
  TVD?: TartuGecko;
  KHR?: TartuGecko;
  CUC?: TartuGecko;
  CUP?: TartuGecko;
  PYG?: TartuGecko;
  MXN?: TartuGecko;
  TRY?: TartuGecko;
  BZD?: TartuGecko;
  BBD?: TartuGecko;
  FKP?: TartuGecko;
  SGD?: TartuGecko;
  LKR?: TartuGecko;
  QAR?: TartuGecko;
  CNY?: TartuGecko;
  PEN?: TartuGecko;
  GGP?: TartuGecko;
  BHD?: TartuGecko;
  ZMW?: TartuGecko;
  CLP?: TartuGecko;
  RON?: TartuGecko;
  MOP?: TartuGecko;
  DKK?: TartuGecko;
  FOK?: TartuGecko;
  BIF?: TartuGecko;
  SHP?: TartuGecko;
  FJD?: TartuGecko;
  GYD?: TartuGecko;
  ETB?: TartuGecko;
  SLL?: TartuGecko;
  PHP?: TartuGecko;
  MZN?: TartuGecko;
  ERN?: TartuGecko;
  VUV?: TartuGecko;
  SBD?: TartuGecko;
  ALL?: TartuGecko;
  CHF?: TartuGecko;
  RUB?: TartuGecko;
  CAD?: TartuGecko;
  GEL?: TartuGecko;
  BDT?: TartuGecko;
  DOP?: TartuGecko;
  KRW?: TartuGecko;
  HKD?: TartuGecko;
  UGX?: TartuGecko;
  KID?: TartuGecko;
  GMD?: TartuGecko;
  JPY?: TartuGecko;
  CKD?: TartuGecko;
  BTN?: TartuGecko;
  CVE?: TartuGecko;
  BWP?: TartuGecko;
  GIP?: TartuGecko;
  SZL?: TartuGecko;
  UAH?: TartuGecko;
  SEK?: TartuGecko;
  PAB?: TartuGecko;
  BMD?: TartuGecko;
  ISK?: TartuGecko;
  VES?: TartuGecko;
  AFN?: TartuGecko;
  BND?: TartuGecko;
  CDF?: TartuGecko;
  KPW?: TartuGecko;
  OMR?: TartuGecko;
  AED?: TartuGecko;
  VND?: TartuGecko;
  GTQ?: TartuGecko;
  IDR?: TartuGecko;
  ARS?: TartuGecko;
  COP?: TartuGecko;
  MKD?: TartuGecko;
  DJF?: TartuGecko;
  AMD?: TartuGecko;
  LSL?: TartuGecko;
  TND?: TartuGecko;
  STN?: TartuGecko;
  SAR?: TartuGecko;
  PLN?: TartuGecko;
  HTG?: TartuGecko;
  SYP?: TartuGecko;
  PKR?: TartuGecko;
  SCR?: TartuGecko;
  SDG?: BAM;
  MWK?: TartuGecko;
  LRD?: TartuGecko;
  MYR?: TartuGecko;
  UZS?: TartuGecko;
  MMK?: TartuGecko;
  SOS?: TartuGecko;
  KMF?: TartuGecko;
  YER?: TartuGecko;
  MUR?: TartuGecko;
}

export interface TartuGecko {
  name: string;
  symbol: string;
}

export interface BAM {
  name: string;
}

export interface Demonyms {
  eng: Eng;
  fra?: Eng;
}

export interface Eng {
  f: string;
  m: string;
}

export interface Flags {
  png: string;
  svg: string;
  alt?: string;
}

export interface Idd {
  root?: string;
  suffixes?: string[];
}

export interface Maps {
  googleMaps: string;
  openStreetMaps: string;
}

export interface Name {
  common: string;
  official: string;
  nativeName?: { [key: string]: Translation };
}

export interface Translation {
  official: string;
  common: string;
}

export interface PostalCode {
  format: string;
  regex?: string;
}

export enum Region {
  Africa = 'Africa',
  Americas = 'Americas',
  Antarctic = 'Antarctic',
  Asia = 'Asia',
  Europe = 'Europe',
  Oceania = 'Oceania',
}

export enum StartOfWeek {
  Monday = 'monday',
  Saturday = 'saturday',
  Sunday = 'sunday',
}

export enum Status {
  OfficiallyAssigned = 'officially-assigned',
  UserAssigned = 'user-assigned',
}
